version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn admin_totalcom.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/var/www/admin_totalcom/staticfiles
      - media_volume:/var/www/admin_totalcom/mediafiles
    expose:
      - 8000
    env_file: .env
    depends_on:
      - db
  db:
    image: keinos/sqlite3:latest
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/var/www/admin_totalcom/staticfiles
      - media_volume:/var/www/admin_totalcom/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
